[package]
name = "json"
version = "0.1.0"
edition = "2021"
authors = ["ItsMeViipeR"]
description = "A Rust crate who allows you to use json files easily"
license = "MIT"

[dependencies]
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.91"
